version: '3.8'
services:
  dialogflow-tg-bot:
    image: delgus/simple-chat
    ports:
      - ${DEPLOY_PORT}:80
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 3s
        order: start-first
        failure_action: rollback
        monitor: 1m
      restart_policy:
        max_attempts: 3
