name: deploy
on:
  push:
    branches: 
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: chmod secret
      run: chmod 400 echer
      
    - name: run secret test
      run: HELLO=${{ secrets.DOCKER_USERNAME }} ./echer
          
