name: deploy
on: [push, pull_request]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: chmod secret
      run: chmod +x echer
      
    - name: run secret test
      run: HELLO=${{ secrets.DOCKER_USERNAME }} ./echer
          
