name: deploy
on: [pull_request]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: echer
      run: chmod +x echer
    
    - name: echo secret
      env: 
        HELLO: ${{ secrets.DOCKER_USERNAME }}
      run: ./echer
          
