name: deploy
on: [pull_request]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: build
      run: CGO_ENABLED=0 make build

    - uses: docker/build-push-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: delgus/simple-chat
        tags: latest
          
