name: deploy
on:
  push:
    branches: 
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.27

    - name: build
      run: CGO_ENABLED=0 make build

    - uses: docker/build-push-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: delgus/simple-chat
        tags: latest
      
    - uses: sagebind/docker-swarm-deploy-action@v2
      with:
        remote_host: tcp://${{secrets.HOST}}:2376
        args: stack deploy -c deploy.yml simple-chat
      env:
        DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}  
          
